apiVersion: batch/v1
kind: Job
metadata:
  name: "traefik-storeconfig-job"
  labels:
    app: traefik
    stack: lb
spec:
  template:
    metadata:
      name: "traefik-storeconfig-job"
      labels:
        app: traefik
        stack: lb
    spec:
      restartPolicy: Never
      containers:
      - name: traefik-storeconfig-job
        image: traefik:1.7-alpine
        args: ["storeconfig"]
        volumeMounts:
        - name: config
          mountPath: /etc/traefik/traefik.toml
          subPath: traefik.toml
        - name: logs
          mountPath: /var/log/traefik
      volumes:
      - name: config
        configMap:
          name: traefik
      - name: logs
        hostPath:
          path: /data/traefik/logs
